language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "4.2"

sudo: false

services:
    - cassandra

notifications:
  email:
    - services@wikimedia.org

script: sh test/utils/run_tests.sh coverage all 2>&1 && (npm run-script coveralls || exit 0)
